Exploratory Data Analysis of Online Food Delivery Ecosystem ft.Zomato

This project analyzes factors influencing restaurant ratings,pricing and customer preferences in an onine food delivery platform using Python.

Tools Used :
 - Python
 - Pandas
 - Google Colab

IMPORT AND LOAD

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("zomato.csv")

OVERVIEW

In [5]:
df.shape
df.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [6]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51717 entries, 0 to 51716
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   url                          51717 non-null  object
 1   address                      51717 non-null  object
 2   name                         51717 non-null  object
 3   online_order                 51717 non-null  object
 4   book_table                   51717 non-null  object
 5   rate                         43942 non-null  object
 6   votes                        51717 non-null  int64
 7   phone                        50509 non-null  object
 8   location                     51696 non-null  object
 9   rest_type                    51490 non-null  object
 10  dish_liked                   23639 non-null  object
 11  cuisines                     51672 non-null  object
 12  approx_cost(for two people)  51371 non-null  object
 13  reviews_list                 51717 non-null  object
 14  menu_item                    51717 non-null  object
 15  listed_in(type)              51717 non-null  object
 16  listed_in(city)              51717 non-null  object
dtypes: int64(1), object(16)
memory usage: 6.7+ MB

              votes
count  51717.000000
mean     283.697527
std      803.838853
min        0.000000
25%        7.000000
50%       41.000000
75%      198.000000
max    16832.000000

DATA QUALITY CHECK

In [8]:
df.isnull().sum()
df.duplicated().sum()

np.int64(0)

CLEANING

In [10]:
df = df.drop_duplicates()
df.columns = df.columns.str.strip()

In [11]:
df['rate'] = df['rate'].str.replace('/5','')

In [12]:
df['rate'] = pd.to_numeric(df['rate'],errors='coerce')

In [13]:
df['approx_cost(for two people)'] = pd.to_numeric(
    df['approx_cost(for two people)'].str.replace(',',''),
    errors='coerce'
)

HANDLING MISSING COLUMNS

In [19]:
df = df.dropna(subset=['rate','approx_cost(for two people)','location'])
df = df.drop(columns=['phone'])

DERIVED COLUMNS

In [20]:
df['price_category'] = pd.cut(
    df['approx_cost(for two people)'],
    bins=[0,500,1000,2000,6000],
    labels=['Low','Medium','High','Luxury']
)

FILTERING

In [21]:
high_rated = df[df['rate'] > 4]
high_rated.head()

,url,address,name,online_order,book_table,rate,votes,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city),price_category
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1,775,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800.0,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari,Medium
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1,787,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800.0,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari,Medium
7,https://www.zomato.com/bangalore/onesta-banash...,"2469, 3rd Floor, 24th Cross, Opposite BDA Comp...",Onesta,Yes,Yes,4.6,2556,Banashankari,"Casual Dining, Cafe","Farmhouse Pizza, Chocolate Banana, Virgin Moji...","Pizza, Cafe, Italian",600.0,"[('Rated 5.0', 'RATED\n I personally really l...",[],Cafes,Banashankari,Medium
9,https://www.zomato.com/bangalore/smacznego-ban...,"2470, 21 Main Road, 25th Cross, Banashankari, ...",Smacznego,Yes,No,4.2,504,Banashankari,Cafe,"Waffles, Pasta, Coleslaw Sandwich, Choco Waffl...","Cafe, Mexican, Italian, Momos, Beverages",550.0,"[('Rated 4.0', ""RATED\n Easy to locate\nVFM 3...",[],Cafes,Banashankari,Medium
10,https://www.zomato.com/bangalore/caf%C3%A9-dow...,"12,29 Near PES University Back Gate, D'Souza N...",CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ© Down The A...,Yes,No,4.1,402,Banashankari,Cafe,"Waffles, Pasta, Crispy Chicken, Honey Chilli C...",Cafe,500.0,"[('Rated 4.0', 'RATED\n We ended up here on a...",[],Cafes,Banashankari,Low

AGGREGATION

In [22]:
df.groupby('location')['rate'].mean()

location
BTM                  3.571659
Banashankari         3.649866
Banaswadi            3.492161
Bannerghatta Road    3.506260
Basavanagudi         3.671092
                       ...
West Bangalore       3.366667
Whitefield           3.623209
Wilson Garden        3.536364
Yelahanka            3.700000
Yeshwantpur          3.502679
Name: rate, Length: 92, dtype: float64

In [23]:
df.shape
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 41418 entries, 0 to 51716
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   url                          41418 non-null  object
 1   address                      41418 non-null  object
 2   name                         41418 non-null  object
 3   online_order                 41418 non-null  object
 4   book_table                   41418 non-null  object
 5   rate                         41418 non-null  float64
 6   votes                        41418 non-null  int64
 7   location                     41418 non-null  object
 8   rest_type                    41271 non-null  object
 9   dish_liked                   23327 non-null  object
 10  cuisines                     41410 non-null  object
 11  approx_cost(for two people)  41418 non-null  float64
 12  reviews_list                 41418 non-null  object
 13  menu_item                    41418 non-null  object
 14  listed_in(type)              41418 non-null  object
 15  listed_in(city)              41418 non-null  object
 16  price_category               41418 non-null  category
dtypes: category(1), float64(2), int64(1), object(13)
memory usage: 5.4+ MB

In [24]:
df.to_csv("zomato_cleaned.csv",index=False)